### ISSUE TITLE
Adopt branch from https://github.com/chunlinyao/fop

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/xmlgraphics-fop#1]
We should import branches from https://github.com/chunlinyao/fop for vertical layout.

**Comment by Intelligent2013** [comment]
The changes from `https://github.com/chunlinyao/fop` (branch `yao-2_9`) will be integrated into the branch `vertical_layout`

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/xmlgraphics-fop/pull/6.
