### ISSUE TITLE
Vertical layout: Japanese text isn't rotated in fo:block-container and fo:table

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/xmlgraphics-fop#8]
Apache FOP source code with vertical layout support: https://github.com/metanorma/xmlgraphics-fop/tree/feature/vertical_layout
XSL-FO sample: https://github.com/metanorma/xmlgraphics-fop/blob/feature/vertical_layout/fop/examples/fo/japanese/vertical_writing.fo

The text in `fo:block`:
```xml
<fo:block border="1pt solid blue" language="JA">
    「天の人を生ずるは億兆皆同一轍にて、之に附与するに動かす可からざるの通義を以てす。即ち其通義とは人の自から生命を保し自由を求め幸福を祈るの類にて、他より之を如何ともす可らざるものなり。」
    ――『アメリカ独立宣言』
</fo:block>
```
renders properly:
![image](https://github.com/user-attachments/assets/291ff016-e5fe-4d1b-8b80-6118ba96ecb3)

The text in `fo:block-container`:
```xml
<fo:block-container>
  <fo:block border="1pt solid blue" language="JA">
    「天の人を生ずるは億兆皆同一轍にて、之に附与するに動かす可からざるの通義を以てす。即ち其通義とは人の自から生命を保し自由を求め幸福を祈るの類にて、他より之を如何ともす可らざるものなり。」
    ――『アメリカ独立宣言』
  </fo:block>
</fo:block-container>
```
and in `fo:table`:
```xml
<fo:table width="100%" table-layout="fixed">
  <fo:table-body>
    <fo:table-row>
      <fo:table-cell>
        <fo:block border="1pt solid blue" language="JA">
            「天の人を生ずるは億兆皆同一轍にて、之に附与するに動かす可からざるの通義を以てす。即ち其通義とは人の自から生命を保し自由を求め幸福を祈るの類にて、他より之を如何ともす可らざるものなり。」
            ――『アメリカ独立宣言』
        </fo:block>
      </fo:table-cell>
    </fo:table-row>
  </fo:table-body>
</fo:table>
```

renders with non-rotated glyphs:
![image](https://github.com/user-attachments/assets/378fb008-13b2-4f64-a671-7830a693e5a3)

![image](https://github.com/user-attachments/assets/3a517b03-364f-414b-80aa-3f0f52958668)

**Comment by SmartWolf1220** [comment]
Hello @Intelligent2013 , I have contributed many open-source projects and I wanted to contribute to your projects.
I have a rich knowledge of Java and Python.
Should I work for this repo?
Looking forward to hearing from you.

**Comment by Intelligent2013** [comment]
@igor-vasilev thank you! Great update!
